version: "3.7"

services:
  blog_app: &app
    build:
      dockerfile: Dockerfile
      context: .
    container_name: blog_app
    command: >
      bash -c "python3 manage.py makemigrations --noinput && python3 manage.py migrate --noinput && python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=true
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=kursach_blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    restart: always
    volumes:
      - .:/app:delegated # enable hot code reload in debug mode
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  postgres:
    image: postgres:latest
    container_name: club_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kursach_blog
    ports:
      - 5432